### ISSUE TITLE
[BUG] Books mark as completely finished in AudiobookShelf as soon as I start playing a book in Plappa

### ISSUE THREAD

**Issue by mindtakerr** [LeoKlaus/plappa#144]
**Describe the bug**
Recently, if I start listening to a book in Plappa, it marks the entire book as complete, no matter how far into the book I am. This did not use to happen.

**To Reproduce**
1. Go to a book in Plappa
2. Click play
3. Look at book on Audiobookshelf, it shows as completed.

**Expected behavior**
Expected behavior is that Audiobookshelf would show the same amount of completion in the book as I have reached in Plappa.

**Screenshots**
![Screenshot 2024-07-01 at 1 18 46 PM](https://github.com/LeoKlaus/plappa/assets/1484215/2c357b75-f61b-421f-a557-ad7f8d0e1812)

![image](https://github.com/LeoKlaus/plappa/assets/1484215/9829ee14-e761-43fd-8323-b23ae6bc3b47)

**Logs**
[7/1/2024, 1:20 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates [7/1/2024, 1:20 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates

**Environment(please complete the following information):**
 - Device: iPhone 14
 - OS: 17.5.1
 - Version 1.2.0
 - Server Version Audiobookshelf 2.10.1

**Additional context**
This did not happen until recently. The location in plappa in the book is correct, but not in ABS.

**Comment by LeoKlaus** [comment]
Thank you for reaching out!

This issue is already fixed in the latest TestFlight release (you can join here if you don't want to wait https://testflight.apple.com/join/oSAekRD5). 

It's a purely cosmetic issue, the progress itself is still correctly tracked.

I still have some issues to fix before this update is ready for the AppStore and I'm due for my exams this week, so it'll probably be another week or so before the AppStore version gets the update.

**Comment by mindtakerr** [comment]
Awesome! Thanks for letting me know!

**Comment by LeoKlaus** [comment]
1.3.0 is also live on the AppStore now!
