### ISSUE TITLE
Support accessing individual books (audio tracks) within a collection

### ISSUE THREAD

**Issue by chancez** [LeoKlaus/plappa#177]
I'm trying to get my wife to use Plappa/ABS but she's mid way into a few collections and it's pretty much impossible to figure out where to start within a given collection. Is there a way for her to just work within a given book in an existing collection? If not: consider it a feature request. Thanks.

**Comment by chancez** [comment]
It might also be my library isn't completely correctly organized that's part of the problem I'm realizing, but it could be nice to support this either way.

**Comment by LeoKlaus** [comment]
Hey Chance, thank you for the suggestion.

I don't think I quite understand what you're asking for. Opening a collection will show each book in that collection as an individual file:
![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-24 at 12 10 23](https://github.com/user-attachments/assets/b1770fc9-110e-4e13-b906-c924038332dc)
and each book will have (if applicable) it's individual chapters listed in its overview.

**Comment by chancez** [comment]
I'm learning that I just have things improperly organized. Here's a "book" with multiple audio books in it, each being a separate "audio track".

![Screenshot 2024-08-22 at 1 34 25 PM](https://github.com/user-attachments/assets/388fef5a-2b03-40a7-8ce3-32652cca39d5)

The proper fix is to put each of these into their own directory, but it could be useful to be able to select individual audiotracks within Plappa regardless.

**Comment by LeoKlaus** [comment]
When viewing an individual book, you should see its chapters like this:
![image](https://github.com/user-attachments/assets/906ff3d5-21f1-422e-b377-7bf8092beab5)

In your case, the chapters of all three books should be listed in order. If a book doesn't have chapters in ABS and its files don't have embedded chapters, plappa will show the individual files instead of chapters.

Is this what you meant or do you think there should be a separate tab for files regardless?

**Comment by chancez** [comment]
I was thinking it should have the _option_ to play by individual file, but honestly I just fixed my library up and now it's not an issues, so you can feel free to ignore this request.
