### ISSUE TITLE
[BUG] ABS Server Version 2.16.x breaks streaming - only downloaded books can be played

### ISSUE THREAD

**Issue by bdux** [LeoKlaus/plappa#208]
**Describe the bug**
After updating my ABS Server to 2.16.0 and 2.16.1 after that, streaming stopped working. I have to download a book to listen to it on my phone. Reverting the server back to 2.15.1 fixed the issue.

**To Reproduce**
Update Server to 2.16.x
Try to stream a book.

**Expected behavior**
Streaming a book works, no download is needed.

**Environment(please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 18.0
 - Version Plappa 1.4.3
 - Server Version Audiobookshelf 2.16.x

**Comment by LeoKlaus** [comment]
This is a known issue with 2.16.1. For now, it's best to stay at 2.16.0 or lower.

I've already reported this to the ABS team and it [seems they have implemented a fix](https://github.com/advplyr/audiobookshelf/pull/3553#issuecomment-2445197382).

I'll let you know once the next version is released an this problem is fixed.

**Comment by LeoKlaus** [comment]
Version 2.16.2 of ABS was just released with a fix for this issue.

I'll leave this open for a day or two so other users can see it.

**Comment by bdux** [comment]
Can confirm that it works again.
