### ISSUE TITLE
[BUG] Bookmark notes text color in iOS is invisible/white on while background

### ISSUE THREAD

**Issue by t18n** [LeoKlaus/plappa#68]
**Describe the bug**
Bookmark notes text color in iOS is invisible/white on while background on **light mode**

**To Reproduce**
1. Go to an Audiobook
2. Click on Note
3. Type something
5. See error

**Expected behavior**
Text should be visible

**Environment(please complete the following information):**
 - Device: iPhone XS
 - Server Version: Audiobookshelf v2.8.1

**Comment by LeoKlaus** [comment]
Hey, thanks for reporting this!
There's already an issue for this bug at #55. It's closed because I've already implemented a fix for this.

The corresponding update should release in TestFlight today and the AppStore in the coming week.

If you have any other feedback or suggestions, feel free to let men know!
