### ISSUE TITLE
[FEATURE REQUEST] Support Search and sorting within a book

### ISSUE THREAD

**Issue by wfrank21** [LeoKlaus/plappa#76]
**Describe the bug**
Searching is possible in the books overview but not in a book directly. Also the sorting seems all over the place, I cannot listen to a book in order without scrolling through 100+ files.

**To Reproduce**
Go to books
Click on book
See that all files are in random order

**Expected behavior**
Sorting by name and a search box within a book view would be nice

**Environment(please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 17.4.1
 - Version 1.1.3
 - Server Version Jellyfin 10.8.13

**Comment by LeoKlaus** [comment]
Hey wfrank21, thanks for reaching out!

The files you see when tapping a book should only be the chapters for that one book. If that's not the case for you, it would help me if you could try to provide some more information about the files you're trying to listen to and how they're stored (you can look at an example [here](https://plappa.me/docs/tutorial-basics/file-storage))

plappa will sort the files for an audiobook by their track number and group files by the "album" attribute in Jellyfin.
I don't think sorting chapters by anything but their number makes sense, but I could certainly add a search bar.

I feel like the issue here is more that plappa groups more than one book in your case so the interface might look/feel very cluttered.
This is what it should look like for a single book:
![image](https://github.com/LeoKlaus/plappa/assets/66492595/b44915ea-53a1-4d36-acc8-e3f14f537def)

**Comment by wfrank21** [comment]
Yeah my problem here is that seemingly all tracks have track number 1. But changing this for hundreds of files would be a pain. So just having the option to sort by name would help me here.

**Comment by LeoKlaus** [comment]
> But changing this for hundreds of files would be a pain. So just having the option to sort by name would help me here.

You can use something like [MP3Tag](https://mp3tag.app/get/) to automatically assign ascending track numbers to all files in a folder:
<img width="1142" alt="image" src="https://github.com/LeoKlaus/plappa/assets/66492595/f7530aa9-df37-4894-a39d-83cb64338485">

This is a quickest fix I can offer you. plappa uses the index number of each track not only for determining the file to play, but also to track progress and decide which file to play next.

I'm looking for a solution to assign ascending track numbers by default, as all files having track number 1 does indeed break everything.

**Comment by LeoKlaus** [comment]
Okay, I think I managed to implement a fix. You can join the TestFlight Beta for plappa at this link: https://testflight.apple.com/join/CPlREvRs
and download the latest version (1.1.4 Build 5).

You will have to go into the book detail view for the affected books and pull down to refresh once for the fix to work (or just uninstall plappa before installing from TestFlight).

**Comment by wfrank21** [comment]
Hi there, this is great news. I will try that today. Joined Testflight already.

**Comment by LeoKlaus** [comment]
Great! Let me know if it worked :)

**Comment by wfrank21** [comment]
Numbering is still not the way I would order it, but at least I can play the correct track now. I will use MP3Tag as a workaround.

**Comment by LeoKlaus** [comment]
> Numbering is still not the way I would order it, but at least I can play the correct track now. I will use MP3Tag as a workaround.

Alright, I'll see if I can add something to make this more seamless.
You may also want to check out [AudioBookShelf](https://www.audiobookshelf.org/), it's a self hostable media server sepcifically for audiobooks and podcasts and it's supported by plappa as well.
It would allow you to add the show as podcast rather than audiobook which would make plappa keep the progress for individual episodes (sorting for those is coming soon).

**Comment by wfrank21** [comment]
Hi there,
I set up an Audiobookshelf Server now with the same files which I have in Jellyfin. Sadly Plappa has the same issue here: Sorting is all over the place. You said sorting is coming soon, so just wanted to give you feedback there. 
For Jellyfin the MP3Tag Trick you told me fixed my problems. Wanted to try Audiobookshelf as it's a specifically for podcasts, will use Jellyfin until sorting for Audiobookshelf is ready.
Thank you for your help

**Comment by LeoKlaus** [comment]
> Hi there, I set up an Audiobookshelf Server now with the same files which I have in Jellyfin. Sadly Plappa has the same issue here: Sorting is all over the place. You said sorting is coming soon, so just wanted to give you feedback there. For Jellyfin the MP3Tag Trick you told me fixed my problems. Wanted to try Audiobookshelf as it's a specifically for podcasts, will use Jellyfin until sorting for Audiobookshelf is ready. Thank you for your help

I tried around a bit with ABS and noticed that when uploading files, all the dates have a different format that was not correctly interpreted by plappa.

I've now fixed those issues and have added sorting for podcast episodes with the latest TestFlight release (1.1.5 build 8).
You can join the TestFlight beta and see if that improves the situation with your ABS server here: https://testflight.apple.com/join/CPlREvRs

**Comment by wfrank21** [comment]
This is perfect. 
![IMG_1491](https://github.com/LeoKlaus/plappa/assets/73826476/5e29a655-7f13-4bc9-bb5a-ba6458343ee8)

**Comment by LeoKlaus** [comment]
I'll close this for now as I think it is no longer needed.

If you feel otherwise, please reopen this issue.
